version: '3.8'
services:
    frontend:
        networks:
            - react-express
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/usr/src/app
            - /usr/src/app/node_modules
        container_name: frontend
        #image: frontend
        build: ./frontend
    backend:
        networks:
            - react-express
            - express-mongo
        volumes:
            - ./backend:/usr/src/app
            - /usr/src/app/node_modules
        container_name: backend
        #image: backend
        build: ./backend
    mongo:
        networks:
            - express-mongo
        volumes:
            - ./data:/data/db
        container_name: mongo
        image: mongo
networks:
    react-express:
        external: true
    express-mongo:
        external: true